name: Deploy Application

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - qa
        - stg
        - prod
env:
  ENVIRONMENT: ${{ inputs.environment }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploying to Dev Environment
      run: |
        echo "The SHA of this commit is: ${GITHUB_SHA}"
    - name: ECHO environment
      run: |
        echo "Environment is: $ENVIRONMENT"
  

    # - name: Set up Node.js
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: 14

    # - name: Stage 1 - Prepare environment
    #   run: |
    #     echo "Preparing environment..."
    #     sudo apt-get update

    # - name: Stage 2 - Install dependencies
    #   run: |
    #     echo "Installing dependencies..."
    #     sudo apt-get install -y libsodium-dev