name: Execute Linux Commands

on:
  push:
    branches:
      - feature/aws_deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Stage 1 - Prepare environment
      run: |
        echo "Preparing environment..."
        sudo apt-get update

    - name: Stage 2 - Install dependencies
      run: |
        echo "Installing dependencies..."
        sudo apt-get install -y libsodium-dev

    - name: Stage 3 - Build project
      run: |
        echo "Building project..."
        npm install
        npm run build

    - name: Stage 4 - Run tests
      run: |
        echo "Running tests..."
        npm test