name: Execute Linux Commands

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute commands
      run: |
        echo "Running command 1"
        echo "executing terraform plan"